default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :tests do
    ENV['FASTLANE_XCODE_LIST_TIMEOUT'] = '600'
    run_tests(
      devices: "iPhone 14 Pro",
      reinstall_app: true,
      scheme: "velib-map"
    )
  end
end
