disabled_rules:
  - trailing_whitespace
  - switch_case_alignment
  - force_unwrapping
  - force_cast
opt_in_rules:
  - empty_count
  - empty_string
  - first_where
  - private_action
  - private_outlet
  - toggle_bool
  - strong_iboutlet
  - implicit_return
analyzer_rules:
  - unused_declaration
included:
  - velib-map
excluded:
  - Pods
  - velib-mapTests

line_length: 200

type_body_length:
  - 300 # warning
  - 400 # error

file_length:
  warning: 500
  error: 1200

type_name:
  min_length: 3 # only warning
  max_length:
    warning: 40
    error: 50
  excluded:
    - K
identifier_name:
  min_length:
    error: 3
  excluded:
    - id
    - URL
    - GlobalAPIKey
    - API_CLIENT_ID
    - vc
    - xy
reporter: "xcode"
