name: run-tests
on:
  pull_request:
    branches:
      - 'develop'
jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: swift-actions/setup-swift@v1
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.0'
      - uses: actions/checkout@v3
      - uses: maierj/fastlane-action@v2.2.0
        with:
          lane: 'tests'
          subdirectory: 'app/fastlane'
